### ISSUE TITLE
mysql container keeps restarting

### ISSUE THREAD

**Issue by aufawibowo** [lephleg/laravel-lumen-docker#3]
When running `docker-compose up -d` I got this issue.
![image](https://user-images.githubusercontent.com/22342569/65832848-c9ad0300-e2f3-11e9-8f6b-1ee8a31b2be4.png)

How do I got into this issue:
I was following the thid step that you had mentioned, and I got that issue.

**Comment by lephleg** [comment]
Hello @aufawibowo,

Please ensure you have created the required password files in the same directory project directory (`db_root_password.txt` and `db_password.txt`). 

Then delete the mysql container and rerun the `docker-compose up -d` command.
